config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#home'
  resources :users
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  

  
  resources :user_meals
  resources :ratings
  resources :comments
  resources :meals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_meals
    has_many :meals, through: :user_meals


    has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authenticate_user, only: [:new, :create]
    before_action :find_user, only: [:edit, :update, :show, :destroy]
    def index
        @user_meals = UserMeal.where(user_id: session[:user_id])
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            flash[:success] = ["All set, exited to prep with you", "Create a week to get Started"]
            redirect_to user_path(@user)
        else
            flash[:my_errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
        
    end
    
    def edit
    end
    
    def update
        @user.update(user_params)
        redirect_to user_path(@user)
    end
    
    def show
    end 
    
    def destroy
        @user.destroy
        redirect_to home_page_path
    end

    private
    def user_params
        params.require(:user).permit(:name, :username, :password, :password_confirmation, :email, :img_url)
    end

    def find_user
        @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<%= f.label :name %><br/>
<%= f.text_field :name %><br/>

<%= f.label :email %><br/>
<%= f.text_field :email %><br/>

<%= f.label :username %><br/>
<%= f.text_field :username %><br/>

<%= f.label :password %><br/>
<%= f.password_field :password %><br/>

<%= f.label :password_confirmation %><br/>
<%= f.password_field :password_confirmation %><br/>

<%= f.label :img_url %><br/>
<%= f.text_field :img_url %><br/>

<%= f.submit %>
    
<% end %>

app/views/users/home.html.erb
<div class="login">
    <%= form_for :session do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :password %>
    <%= f.text_field :password %>
  
    <%= f.submit class: 'button'%>
  <% end %>
  </div>
  <%= button_to("Let's Start Planning", new_user_path, { :method => :get, :class => 'special_button' })%>
  <div class="bg1">
    <%= image_tag("https://lh3.googleusercontent.com/mglGpp8yC2qCvNH8jWA_r01LM1tEbaEy0c_G9KTuB9qSiRI4IWgAjiQ_3u6KfAJVHeqfZ-E8dwq4fHcVNIPFovr3viY-7zpSZpjfg2z9wEGs-ZzS_Xof4pURl6BQO1Lmu-hAHCKWaD45tR92cxLXu6muXwQPPj-p8l-YDEBm7sADjL-Qt4nyP-KQPMISH3f55Us4fAVHzV0QdPt9zR8RwTgTRHPc15EM_6mNWz5sCFMtGyylgNiVBgeoQB0-oqV8J57X5CRkM_fSI86C0YEBnBS-tX-_Fh34Hyp6CGttq48EX3Vi9a74zbSrv-jAvdAiRCi5qRdN0WFcQb7uXU9cX7_ZRUjC_IZs2-WXEz0HrMWEde8O6N_E1ekAPJ0mXeLjcg4q9pEDBuOO3pDW7jvSaIDxxvbOmFAZmFQ_2WW3pGUcuXcysvenmiyX72124wPnumsM_5qEctYQQ8MzAp033IIUsCD3GvPzy9eH9Ks0oiIRDZoRbTZf0r1rKvcrEs_jHBHHC4pnYEGL7zrF2a0I4NYUZR6JjloIYuHb3PfFoNjOYCp7MyP_vZiTuwK7VfeBvPm94IlIoVbpN2uhkL2O_yUz6-kM0ickamoFrzg9NWJpjznGepZ-2Ygg26cVoNCW4eBMikcyJ8gmYeQ4fxLFAnBBqgtQMDd5XTh2Kt-8uZrytldnJWyA5AM3EhR6Mg=w1948-h1504-no", width: "100%") %>
  
  
  
  
  
  </div> 

app/views/users/index.html.erb
 <h2>Welcome to your Planned Meals</h2>



 <% if @user_meals %>
  <% @user_meals.each do |us_me| %>
    <h3><%= link_to us_me.meal.name, meal_path(us_me.meal) %></h3>
    <img src="<%= us_me.meal.img_url %>"" alt="<%= us_me.meal.name %>">
    <p><%= us_me.meal_type  %> on <%= us_me.month_name%>- <%= us_me.date.day%> At: <%= us_me.oclock %> </p>


  <%= link_to "Delete", user_meal_path(us_me), method: :delete %>
    <% end %>
<% end %>


 <%= link_to "Select a Meal and Set a Date", meals_path %>

app/views/users/show.html.erb
<h1>Profile</h1>


<h4>Name: <%= @user.name %></h4>
<h4>Current Email: <%= @user.email %> </h4>
<img src="<%= @user.img_url%>" alt="<%= @user.name%>" />


 <%= button_to "Delete Account", user_path(@user), method: :delete %>

 <%= link_to '<button type="button">Edit</button>'.html_safe, edit_user_path %>